### ISSUE TITLE
接触

### ISSUE THREAD

**Issue by newcherryberry** [fenghan0430/How-to-use-vGPU#1]
你好 Fenghan，
如果这个 repo 不适合做这件事，我很抱歉，但我找不到其他联系方式！我需要一些帮助来完成你之前做过的一个项目（OpenAnimate）。请告诉我我是否可以给你发邮件，或者你觉得给我发邮件更方便。我真的需要你的帮助——我将不胜感激。
谢谢，
Maylin

**Comment by fenghan0430** [comment]
我在我的主页上添加了我的邮箱，现在你随时可以通过发邮件来联系我
