### ISSUE TITLE
justin-himself大佬的NVIDIA-VGPU-Driver-Archive仓库没了

### ISSUE THREAD

**Issue by wmailn** [fenghan0430/How-to-use-vGPU#2]
如题，justin-himself大佬的NVIDIA-VGPU-Driver-Archive仓库没了，还有其他备选吗？

**Comment by fenghan0430** [comment]
加入这个discord频道，邀请链接：`https://discord.gg/aYUbsecV`(有效期七天)，在这里面找别人分享的连接
