### ISSUE TITLE
A5000报错：无法初始化 vGPU“nvidia_rtxa5000-1b”的插件“libnvidia-vgx.so”。

### ISSUE THREAD

**Issue by wmailn** [fenghan0430/How-to-use-vGPU#6]
你好：
我按照教程配置下来，一切都一模一样，直到最后我在启动创建的虚拟机时，提示：
`无法初始化 vGPU“nvidia_rtxa5000-1b”的插件“libnvidia-vgx.so”。`

我的显卡是A5000，ESXI中驱动正常
ESXi 8.0 U2
BIOS中也开启了SR-IOV

![图片](https://github.com/user-attachments/assets/5a107bf2-7e4e-4876-8a6e-10242898ce72)

![图片](https://github.com/user-attachments/assets/a422e649-75a8-4024-9192-28547467f2f8)

![图片](https://github.com/user-attachments/assets/d009f58d-2c1b-4e1f-bcfa-50bbb6caf314)

![图片](https://github.com/user-attachments/assets/83b6d88c-d30b-420d-902d-ec8bd26a7781)

**Comment by fenghan0430** [comment]
你试试这个：[NV博客链接](https://forums.developer.nvidia.com/t/a6000-in-vgpu-13-0-and-esxi-7-0u2-failed-to-start-vgpu-instance/187822)。

原文翻译：您需要先更改 GPU 模式。A6000(应该适用于A5000) 是一款工作站 GPU，需要切换到显示模式关闭和大 BAR1 大小。下载 modeselector 工具。

工具需要你自己找喽

**Comment by wmailn** [comment]
感谢大佬

**Comment by fenghan0430** [comment]
再试试吧，我觉得官方博客比较靠谱

**Comment by wmailn** [comment]
应该是BIOS某个开关没开，我再研究下。

**Comment by wmailn** [comment]
大佬，搞定了，反馈下：
BIOS要开启以下选项：
"AER Cap" "IOMMU" "ARI Support" "10 Bit Tag Support" "Above 4G Decoding" "SR-IOV Support"
